<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="19" failed="1" ignored="0" total="20" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Promotion" duration-ms="11490" started-at="2023-12-27T01:12:30Z" finished-at="2023-12-27T01:12:42Z">
    <groups>
    </groups>
    <test name="BackOffice" duration-ms="0" started-at="2023-12-27T01:12:30Z" finished-at="2023-12-27T01:12:30Z">
    </test> <!-- BackOffice -->
    <test name="Facade Promotion" duration-ms="0" started-at="2023-12-27T01:12:30Z" finished-at="2023-12-27T01:12:30Z">
    </test> <!-- Facade Promotion -->
    <test name="Test" duration-ms="0" started-at="2023-12-27T01:12:30Z" finished-at="2023-12-27T01:12:30Z">
    </test> <!-- Test -->
    <test name="E2E" duration-ms="11443" started-at="2023-12-27T01:12:30Z" finished-at="2023-12-27T01:12:42Z">
      <class name="E2E.TestSet_H5_MPMSTORE_009_HeiMingDan">
        <test-method status="PASS" signature="init(java.lang.String)[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad]" name="init" is-config="true" duration-ms="116" started-at="2023-12-27T01:12:30Z" finished-at="2023-12-27T01:12:30Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[PP]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="FAIL" signature="test001_启动后台()[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad]" name="test001_启动后台" duration-ms="11418" started-at="2023-12-27T01:12:30Z" finished-at="2023-12-27T01:12:42Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[BackOffice登入失败 expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: BackOffice登入失败 expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at E2E.TestSet_H5_MPMSTORE_009_HeiMingDan.test001_启动后台(TestSet_H5_MPMSTORE_009_HeiMingDan.java:125)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test001_启动后台 -->
        <test-method status="SKIP" signature="test004_活动页黑名单全场券页面获取()[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad]" name="test004_活动页黑名单全场券页面获取" duration-ms="0" started-at="2023-12-27T01:12:42Z" depends-on-methods="E2E.TestSet_H5_MPMSTORE_009_HeiMingDan.test003_创建活动页黑名单全场券" finished-at="2023-12-27T01:12:42Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestSet_H5_MPMSTORE_009_HeiMingDan.test004_活动页黑名单全场券页面获取()[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestSet_H5_MPMSTORE_009_HeiMingDan.test004_活动页黑名单全场券页面获取()[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test004_活动页黑名单全场券页面获取 -->
        <test-method status="SKIP" signature="test003_创建活动页黑名单全场券()[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad]" name="test003_创建活动页黑名单全场券" duration-ms="0" started-at="2023-12-27T01:12:42Z" depends-on-methods="E2E.TestSet_H5_MPMSTORE_009_HeiMingDan.test002_创建活动页面" finished-at="2023-12-27T01:12:42Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestSet_H5_MPMSTORE_009_HeiMingDan.test003_创建活动页黑名单全场券()[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestSet_H5_MPMSTORE_009_HeiMingDan.test003_创建活动页黑名单全场券()[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test003_创建活动页黑名单全场券 -->
        <test-method status="SKIP" signature="test002_创建活动页面()[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad]" name="test002_创建活动页面" duration-ms="0" started-at="2023-12-27T01:12:42Z" depends-on-methods="E2E.TestSet_H5_MPMSTORE_009_HeiMingDan.test001_启动后台" finished-at="2023-12-27T01:12:42Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestSet_H5_MPMSTORE_009_HeiMingDan.test002_创建活动页面()[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestSet_H5_MPMSTORE_009_HeiMingDan.test002_创建活动页面()[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test002_创建活动页面 -->
        <test-method status="SKIP" signature="test010_cartEstimatePrices()[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad]" name="test010_cartEstimatePrices" duration-ms="0" started-at="2023-12-27T01:12:42Z" depends-on-methods="E2E.TestSet_H5_MPMSTORE_009_HeiMingDan.test006_cartEstimatePrices" finished-at="2023-12-27T01:12:42Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestSet_H5_MPMSTORE_009_HeiMingDan.test010_cartEstimatePrices()[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestSet_H5_MPMSTORE_009_HeiMingDan.test010_cartEstimatePrices()[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test010_cartEstimatePrices -->
        <test-method status="SKIP" signature="test006_cartEstimatePrices()[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad]" name="test006_cartEstimatePrices" duration-ms="0" started-at="2023-12-27T01:12:42Z" depends-on-methods="E2E.TestSet_H5_MPMSTORE_009_HeiMingDan.test009_loggedUserReceiveCoupon" finished-at="2023-12-27T01:12:42Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestSet_H5_MPMSTORE_009_HeiMingDan.test006_cartEstimatePrices()[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestSet_H5_MPMSTORE_009_HeiMingDan.test006_cartEstimatePrices()[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test006_cartEstimatePrices -->
        <test-method status="SKIP" signature="test009_loggedUserReceiveCoupon()[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad]" name="test009_loggedUserReceiveCoupon" duration-ms="0" started-at="2023-12-27T01:12:42Z" depends-on-methods="E2E.TestSet_H5_MPMSTORE_009_HeiMingDan.test005_活动页黑名单页面获取" finished-at="2023-12-27T01:12:42Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestSet_H5_MPMSTORE_009_HeiMingDan.test009_loggedUserReceiveCoupon()[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestSet_H5_MPMSTORE_009_HeiMingDan.test009_loggedUserReceiveCoupon()[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test009_loggedUserReceiveCoupon -->
        <test-method status="SKIP" signature="test005_活动页黑名单页面获取()[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad]" name="test005_活动页黑名单页面获取" duration-ms="0" started-at="2023-12-27T01:12:42Z" depends-on-methods="E2E.TestSet_H5_MPMSTORE_009_HeiMingDan.test004_活动页黑名单全场券页面获取" finished-at="2023-12-27T01:12:42Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestSet_H5_MPMSTORE_009_HeiMingDan.test005_活动页黑名单页面获取()[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestSet_H5_MPMSTORE_009_HeiMingDan.test005_活动页黑名单页面获取()[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test005_活动页黑名单页面获取 -->
        <test-method status="SKIP" signature="test011_cartEstimatePrices(xProject.testCase.testCaseTemplateOne)[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad]" name="test011_cartEstimatePrices" duration-ms="0" started-at="2023-12-27T01:12:42Z" data-provider="test011_cartEstimatePrices" depends-on-methods="E2E.TestSet_H5_MPMSTORE_009_HeiMingDan.test010_cartEstimatePrices" finished-at="2023-12-27T01:12:42Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestSet_H5_MPMSTORE_009_HeiMingDan.test011_cartEstimatePrices(xProject.testCase.testCaseTemplateOne)[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestSet_H5_MPMSTORE_009_HeiMingDan.test011_cartEstimatePrices(xProject.testCase.testCaseTemplateOne)[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test011_cartEstimatePrices -->
        <test-method status="SKIP" signature="test013_创建活动页面()[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad]" name="test013_创建活动页面" duration-ms="0" started-at="2023-12-27T01:12:42Z" depends-on-methods="E2E.TestSet_H5_MPMSTORE_009_HeiMingDan.test012_cartEstimatePrices" finished-at="2023-12-27T01:12:42Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestSet_H5_MPMSTORE_009_HeiMingDan.test013_创建活动页面()[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestSet_H5_MPMSTORE_009_HeiMingDan.test013_创建活动页面()[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test013_创建活动页面 -->
        <test-method status="SKIP" signature="test014_创建活动页黑名单全场券()[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad]" name="test014_创建活动页黑名单全场券" duration-ms="0" started-at="2023-12-27T01:12:42Z" depends-on-methods="E2E.TestSet_H5_MPMSTORE_009_HeiMingDan.test013_创建活动页面" finished-at="2023-12-27T01:12:42Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestSet_H5_MPMSTORE_009_HeiMingDan.test014_创建活动页黑名单全场券()[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestSet_H5_MPMSTORE_009_HeiMingDan.test014_创建活动页黑名单全场券()[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test014_创建活动页黑名单全场券 -->
        <test-method status="SKIP" signature="test012_cartEstimatePrices(xProject.testCase.testCaseTemplateOne)[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad]" name="test012_cartEstimatePrices" duration-ms="0" started-at="2023-12-27T01:12:42Z" data-provider="test012_cartEstimatePrices" depends-on-methods="E2E.TestSet_H5_MPMSTORE_009_HeiMingDan.test011_cartEstimatePrices" finished-at="2023-12-27T01:12:42Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestSet_H5_MPMSTORE_009_HeiMingDan.test012_cartEstimatePrices(xProject.testCase.testCaseTemplateOne)[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestSet_H5_MPMSTORE_009_HeiMingDan.test012_cartEstimatePrices(xProject.testCase.testCaseTemplateOne)[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test012_cartEstimatePrices -->
        <test-method status="SKIP" signature="test025_活动页全场券页面获取()[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad]" name="test025_活动页全场券页面获取" duration-ms="0" started-at="2023-12-27T01:12:42Z" depends-on-methods="E2E.TestSet_H5_MPMSTORE_009_HeiMingDan.test015_活动页黑名单全场券页面获取" finished-at="2023-12-27T01:12:42Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestSet_H5_MPMSTORE_009_HeiMingDan.test025_活动页全场券页面获取()[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestSet_H5_MPMSTORE_009_HeiMingDan.test025_活动页全场券页面获取()[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test025_活动页全场券页面获取 -->
        <test-method status="SKIP" signature="test015_活动页黑名单全场券页面获取()[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad]" name="test015_活动页黑名单全场券页面获取" duration-ms="0" started-at="2023-12-27T01:12:42Z" depends-on-methods="E2E.TestSet_H5_MPMSTORE_009_HeiMingDan.test014_创建活动页黑名单全场券" finished-at="2023-12-27T01:12:42Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestSet_H5_MPMSTORE_009_HeiMingDan.test015_活动页黑名单全场券页面获取()[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestSet_H5_MPMSTORE_009_HeiMingDan.test015_活动页黑名单全场券页面获取()[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test015_活动页黑名单全场券页面获取 -->
        <test-method status="SKIP" signature="test021_loggedUserReceiveCoupon()[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad]" name="test021_loggedUserReceiveCoupon" duration-ms="0" started-at="2023-12-27T01:12:42Z" depends-on-methods="E2E.TestSet_H5_MPMSTORE_009_HeiMingDan.test019_cartEstimatePrices" finished-at="2023-12-27T01:12:42Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestSet_H5_MPMSTORE_009_HeiMingDan.test021_loggedUserReceiveCoupon()[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestSet_H5_MPMSTORE_009_HeiMingDan.test021_loggedUserReceiveCoupon()[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test021_loggedUserReceiveCoupon -->
        <test-method status="SKIP" signature="test018_cartEstimatePrices(xProject.testCase.testCaseTemplateOne)[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad]" name="test018_cartEstimatePrices" duration-ms="0" started-at="2023-12-27T01:12:42Z" data-provider="test018_cartEstimatePrices" depends-on-methods="E2E.TestSet_H5_MPMSTORE_009_HeiMingDan.test017_cartEstimatePrices" finished-at="2023-12-27T01:12:42Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestSet_H5_MPMSTORE_009_HeiMingDan.test018_cartEstimatePrices(xProject.testCase.testCaseTemplateOne)[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestSet_H5_MPMSTORE_009_HeiMingDan.test018_cartEstimatePrices(xProject.testCase.testCaseTemplateOne)[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test018_cartEstimatePrices -->
        <test-method status="SKIP" signature="test019_cartEstimatePrices(xProject.testCase.testCaseTemplateOne)[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad]" name="test019_cartEstimatePrices" duration-ms="0" started-at="2023-12-27T01:12:42Z" data-provider="test019_cartEstimatePrices" depends-on-methods="E2E.TestSet_H5_MPMSTORE_009_HeiMingDan.test018_cartEstimatePrices" finished-at="2023-12-27T01:12:42Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestSet_H5_MPMSTORE_009_HeiMingDan.test019_cartEstimatePrices(xProject.testCase.testCaseTemplateOne)[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestSet_H5_MPMSTORE_009_HeiMingDan.test019_cartEstimatePrices(xProject.testCase.testCaseTemplateOne)[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test019_cartEstimatePrices -->
        <test-method status="SKIP" signature="test023_userAvailableCoupon()[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad]" name="test023_userAvailableCoupon" duration-ms="0" started-at="2023-12-27T01:12:42Z" depends-on-methods="E2E.TestSet_H5_MPMSTORE_009_HeiMingDan.test021_loggedUserReceiveCoupon" finished-at="2023-12-27T01:12:42Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestSet_H5_MPMSTORE_009_HeiMingDan.test023_userAvailableCoupon()[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestSet_H5_MPMSTORE_009_HeiMingDan.test023_userAvailableCoupon()[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test023_userAvailableCoupon -->
        <test-method status="SKIP" signature="test016_loggedUserReceiveCoupon()[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad]" name="test016_loggedUserReceiveCoupon" duration-ms="0" started-at="2023-12-27T01:12:42Z" depends-on-methods="E2E.TestSet_H5_MPMSTORE_009_HeiMingDan.test025_活动页全场券页面获取" finished-at="2023-12-27T01:12:42Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestSet_H5_MPMSTORE_009_HeiMingDan.test016_loggedUserReceiveCoupon()[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestSet_H5_MPMSTORE_009_HeiMingDan.test016_loggedUserReceiveCoupon()[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test016_loggedUserReceiveCoupon -->
        <test-method status="SKIP" signature="test017_cartEstimatePrices()[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad]" name="test017_cartEstimatePrices" duration-ms="0" started-at="2023-12-27T01:12:42Z" depends-on-methods="E2E.TestSet_H5_MPMSTORE_009_HeiMingDan.test016_loggedUserReceiveCoupon" finished-at="2023-12-27T01:12:42Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestSet_H5_MPMSTORE_009_HeiMingDan.test017_cartEstimatePrices()[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestSet_H5_MPMSTORE_009_HeiMingDan.test017_cartEstimatePrices()[pri:0, instance:E2E.TestSet_H5_MPMSTORE_009_HeiMingDan@4520ebad] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test017_cartEstimatePrices -->
      </class> <!-- E2E.TestSet_H5_MPMSTORE_009_HeiMingDan -->
    </test> <!-- E2E -->
  </suite> <!-- Promotion -->
</testng-results>
